# Generated by Django 4.2.7 on 2023-11-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Vehicle_Photos')),
                ('type', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('availability', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
